// Urgency Level Definitions (Aligned with standard Emergency Severity Index / ESI & Manchester Triage guidelines)
export const URGENCY_LEVELS = {
  1: {
    level: 1,
    name: 'Immediate',
    code: 'RESUSCITATION',
    description: 'Immediate life-saving intervention needed without delay.',
    badgeClass: 'bg-rose-50 text-rose-700 border-rose-200 ring-1 ring-rose-500/20',
    dotClass: 'bg-rose-600',
    cardBorder: 'border-l-rose-500',
    headerBg: 'bg-rose-500/10 text-rose-700',
    targetReviewTime: '< 2 mins',
  },
  2: {
    level: 2,
    name: 'Emergency',
    code: 'VERY_URGENT',
    description: 'High risk condition, altered mental state, severe pain, or vital instability.',
    badgeClass: 'bg-orange-50 text-orange-700 border-orange-200 ring-1 ring-orange-500/20',
    dotClass: 'bg-orange-500',
    cardBorder: 'border-l-orange-500',
    headerBg: 'bg-orange-500/10 text-orange-700',
    targetReviewTime: '< 15 mins',
  },
  3: {
    level: 3,
    name: 'Urgent',
    code: 'URGENT',
    description: 'Stable vitals, multiple diagnostic resources needed, moderate distress.',
    badgeClass: 'bg-amber-50 text-amber-800 border-amber-200 ring-1 ring-amber-500/20',
    dotClass: 'bg-amber-500',
    cardBorder: 'border-l-amber-500',
    headerBg: 'bg-amber-500/10 text-amber-800',
    targetReviewTime: '< 30 mins',
  },
  4: {
    level: 4,
    name: 'Standard',
    code: 'LESS_URGENT',
    description: 'Stable condition requiring single clinical resource (e.g., X-ray or simple sutures).',
    badgeClass: 'bg-sky-50 text-sky-800 border-sky-200 ring-1 ring-sky-500/20',
    dotClass: 'bg-sky-500',
    cardBorder: 'border-l-sky-500',
    headerBg: 'bg-sky-500/10 text-sky-800',
    targetReviewTime: '< 60 mins',
  },
  5: {
    level: 5,
    name: 'Non-Urgent',
    code: 'ROUTINE',
    description: 'Minor symptoms, prescription renewal, or dressing changes requiring no resources.',
    badgeClass: 'bg-slate-50 text-slate-700 border-slate-200 ring-1 ring-slate-500/20',
    dotClass: 'bg-slate-400',
    cardBorder: 'border-l-slate-400',
    headerBg: 'bg-slate-500/10 text-slate-700',
    targetReviewTime: '< 120 mins',
  },
};

export const PATIENT_STATUS = {
  WAITING: 'Waiting',
  IN_CONSULTATION: 'In Consultation',
  COMPLETED: 'Completed',
};

export const DEPARTMENTS = [
  'Emergency & Trauma',
  'Cardiology',
  'Respiratory & Pulmonology',
  'Pediatrics',
  'Neurology',
  'General Medicine',
];

// 12 Realistic Fictional Demo Patients with varying triage levels and arrival timestamps
export const INITIAL_FICTIONAL_PATIENTS = [
  {
    id: 'pt-001',
    mrn: 'SC-2026-8812',
    fullName: 'Elena Rostova',
    age: 58,
    gender: 'Female',
    phone: '+1 (555) 234-8901',
    department: 'Cardiology',
    chiefComplaint: 'Crushing retrosternal chest pain radiating to left jaw & diaphoresis',
    status: PATIENT_STATUS.WAITING,
    urgencyLevel: 1, // Clinician confirmed Level 1
    clinicianAssessor: 'Dr. Sarah Vance, MD (Attending)',
    arrivalTimestamp: Date.now() - 14 * 60 * 1000, // 14 mins ago
    consultationStartTimestamp: null,
    completionTimestamp: null,
    vitals: {
      bloodPressureSystolic: 185,
      bloodPressureDiastolic: 110,
      heartRate: 118,
      respiratoryRate: 26,
      spO2: 91,
      temperatureC: 37.1,
      painScore: 9,
    },
    preliminaryWarningFlags: [
      'Critical SpO2 (< 92%)',
      'Severe Hypertensive Urgency (> 180 mmHg systolic)',
      'Marked Tachycardia (> 110 bpm)',
      'High Pain Score (9/10)',
    ],
    clinicianNotes: 'ECG immediately ordered. Stat troponin panel sent. Transferred to Resus Bay 1.',
    roomOrBed: 'Resuscitation Bay 1',
  },
  {
    id: 'pt-002',
    mrn: 'SC-2026-4491',
    fullName: 'Marcus Sterling',
    age: 34,
    gender: 'Male',
    phone: '+1 (555) 345-6712',
    department: 'Emergency & Trauma',
    chiefComplaint: 'Blunt thoracic trauma from bicycle collision; respiratory splinting',
    status: PATIENT_STATUS.WAITING,
    urgencyLevel: 2,
    clinicianAssessor: 'Nurse Practitioner J. Miller',
    arrivalTimestamp: Date.now() - 28 * 60 * 1000, // 28 mins ago
    consultationStartTimestamp: null,
    completionTimestamp: null,
    vitals: {
      bloodPressureSystolic: 138,
      bloodPressureDiastolic: 88,
      heartRate: 98,
      respiratoryRate: 24,
      spO2: 94,
      temperatureC: 36.8,
      painScore: 8,
    },
    preliminaryWarningFlags: [
      'Elevated Tachypnea (> 22 breaths/min)',
      'Severe Trauma Pain (8/10)',
    ],
    clinicianNotes: 'Fast ultrasound requested. Evaluate for rib fractures and pneumothorax.',
    roomOrBed: 'Trauma Bed 3',
  },
  {
    id: 'pt-003',
    mrn: 'SC-2026-9021',
    fullName: 'Aaliyah Khan',
    age: 7,
    gender: 'Female',
    phone: '+1 (555) 789-0123',
    department: 'Pediatrics',
    chiefComplaint: 'Acute wheezing and stridor with intercostal retractions; known asthma',
    status: PATIENT_STATUS.IN_CONSULTATION,
    urgencyLevel: 2,
    clinicianAssessor: 'Dr. Michael Chen, MD',
    arrivalTimestamp: Date.now() - 42 * 60 * 1000, // 42 mins ago
    consultationStartTimestamp: Date.now() - 15 * 60 * 1000,
    completionTimestamp: null,
    vitals: {
      bloodPressureSystolic: 104,
      bloodPressureDiastolic: 68,
      heartRate: 128,
      respiratoryRate: 32,
      spO2: 93,
      temperatureC: 38.3,
      painScore: 6,
    },
    preliminaryWarningFlags: [
      'Pediatric Respiratory Distress',
      'Febrile (38.3 °C)',
      'Borderline SpO2 (93%)',
    ],
    clinicianNotes: 'Nebulized albuterol administered. Continuous pulse oximetry monitoring in Pediatric Bay 2.',
    roomOrBed: 'Peds Bay 2',
  },
  {
    id: 'pt-004',
    mrn: 'SC-2026-1185',
    fullName: 'Robert Hayes',
    age: 71,
    gender: 'Male',
    phone: '+1 (555) 456-7890',
    department: 'Neurology',
    chiefComplaint: 'Sudden onset right-sided facial droop and mild slurred speech 45m ago',
    status: PATIENT_STATUS.IN_CONSULTATION,
    urgencyLevel: 1,
    clinicianAssessor: 'Dr. Emily Watson, MD (Neurology)',
    arrivalTimestamp: Date.now() - 55 * 60 * 1000,
    consultationStartTimestamp: Date.now() - 35 * 60 * 1000,
    completionTimestamp: null,
    vitals: {
      bloodPressureSystolic: 172,
      bloodPressureDiastolic: 98,
      heartRate: 84,
      respiratoryRate: 18,
      spO2: 97,
      temperatureC: 36.9,
      painScore: 2,
    },
    preliminaryWarningFlags: [
      'Acute Stroke Code Flag (FAST positive)',
      'Hypertensive (> 170 mmHg)',
    ],
    clinicianNotes: 'Code Stroke protocol initiated. Non-contrast head CT completed; awaiting tPA clearance.',
    roomOrBed: 'Neuro Observation 1',
  },
  {
    id: 'pt-005',
    mrn: 'SC-2026-3329',
    fullName: 'Chloe Dupont',
    age: 26,
    gender: 'Female',
    phone: '+1 (555) 678-9012',
    department: 'Emergency & Trauma',
    chiefComplaint: 'Right lower quadrant abdominal pain with rebound tenderness & nausea',
    status: PATIENT_STATUS.WAITING,
    urgencyLevel: 3,
    clinicianAssessor: 'Nurse Practitioner J. Miller',
    arrivalTimestamp: Date.now() - 35 * 60 * 1000,
    consultationStartTimestamp: null,
    completionTimestamp: null,
    vitals: {
      bloodPressureSystolic: 122,
      bloodPressureDiastolic: 76,
      heartRate: 92,
      respiratoryRate: 18,
      spO2: 99,
      temperatureC: 37.9,
      painScore: 7,
    },
    preliminaryWarningFlags: [
      'Possible Acute Appendicitis',
      'Moderate-to-Severe Pain (7/10)',
    ],
    clinicianNotes: 'Surgical consult notified. IV fluids started; labs ordered including CBC & abdominal ultrasound.',
    roomOrBed: 'Exam Room 4',
  },
  {
    id: 'pt-006',
    mrn: 'SC-2026-5503',
    fullName: 'David O\'Connor',
    age: 63,
    gender: 'Male',
    phone: '+1 (555) 890-1234',
    department: 'Respiratory & Pulmonology',
    chiefComplaint: 'Exacerbation of chronic COPD with productive purulent sputum',
    status: PATIENT_STATUS.WAITING,
    urgencyLevel: 3,
    clinicianAssessor: 'Triage Nurse K. Adams, RN',
    arrivalTimestamp: Date.now() - 48 * 60 * 1000,
    consultationStartTimestamp: null,
    completionTimestamp: null,
    vitals: {
      bloodPressureSystolic: 142,
      bloodPressureDiastolic: 86,
      heartRate: 88,
      respiratoryRate: 22,
      spO2: 92,
      temperatureC: 37.4,
      painScore: 3,
    },
    preliminaryWarningFlags: [
      'Hypoxemia risk in COPD (SpO2 92%)',
      'Mild Tachypnea',
    ],
    clinicianNotes: 'Titrated O2 via Venturi mask. Ordered portable CXR and ABG.',
    roomOrBed: 'Consult Room 2',
  },
  {
    id: 'pt-007',
    mrn: 'SC-2026-7721',
    fullName: 'Sophia Martinez',
    age: 19,
    gender: 'Female',
    phone: '+1 (555) 901-2345',
    department: 'Emergency & Trauma',
    chiefComplaint: 'Inversion injury to left ankle after sports; swollen, unable to bear weight',
    status: PATIENT_STATUS.WAITING,
    urgencyLevel: 4,
    clinicianAssessor: 'Triage Nurse K. Adams, RN',
    arrivalTimestamp: Date.now() - 22 * 60 * 1000,
    consultationStartTimestamp: null,
    completionTimestamp: null,
    vitals: {
      bloodPressureSystolic: 118,
      bloodPressureDiastolic: 74,
      heartRate: 76,
      respiratoryRate: 16,
      spO2: 99,
      temperatureC: 36.6,
      painScore: 5,
    },
    preliminaryWarningFlags: [],
    clinicianNotes: 'Ottawa ankle rules positive for X-ray requirement. Ice & elevation applied.',
    roomOrBed: 'Fast-Track Bay 1',
  },
  {
    id: 'pt-008',
    mrn: 'SC-2026-8842',
    fullName: 'Jameson Wu',
    age: 45,
    gender: 'Male',
    phone: '+1 (555) 123-4567',
    department: 'General Medicine',
    chiefComplaint: 'Persistent migraine headache unresponsive to over-the-counter NSAIDs',
    status: PATIENT_STATUS.WAITING,
    urgencyLevel: 4,
    clinicianAssessor: 'Nurse Practitioner J. Miller',
    arrivalTimestamp: Date.now() - 65 * 60 * 1000,
    consultationStartTimestamp: null,
    completionTimestamp: null,
    vitals: {
      bloodPressureSystolic: 130,
      bloodPressureDiastolic: 82,
      heartRate: 74,
      respiratoryRate: 16,
      spO2: 98,
      temperatureC: 36.8,
      painScore: 6,
    },
    preliminaryWarningFlags: [],
    clinicianNotes: 'Dim light room recommended. Neurologic screening intact.',
    roomOrBed: 'Observation Room 6',
  },
  {
    id: 'pt-009',
    mrn: 'SC-2026-2244',
    fullName: 'Fatima Al-Mansoor',
    age: 38,
    gender: 'Female',
    phone: '+1 (555) 345-8901',
    department: 'General Medicine',
    chiefComplaint: 'Laceration on left index finger from kitchen knife, bleeding controlled',
    status: PATIENT_STATUS.COMPLETED,
    urgencyLevel: 4,
    clinicianAssessor: 'Dr. Sarah Vance, MD',
    arrivalTimestamp: Date.now() - 110 * 60 * 1000,
    consultationStartTimestamp: Date.now() - 60 * 60 * 1000,
    completionTimestamp: Date.now() - 20 * 60 * 1000,
    vitals: {
      bloodPressureSystolic: 124,
      bloodPressureDiastolic: 78,
      heartRate: 72,
      respiratoryRate: 14,
      spO2: 100,
      temperatureC: 36.7,
      painScore: 2,
    },
    preliminaryWarningFlags: [],
    clinicianNotes: 'Simple interrupted sutures (3x 4-0 nylon). Tetanus booster given. Discharged with wound care instructions.',
    roomOrBed: 'Discharged Home',
  },
  {
    id: 'pt-010',
    mrn: 'SC-2026-6631',
    fullName: 'Arthur Pendelton',
    age: 82,
    gender: 'Male',
    phone: '+1 (555) 432-1098',
    department: 'Cardiology',
    chiefComplaint: 'Palpitations and dizziness; irregular pulse detected on smartwatch',
    status: PATIENT_STATUS.IN_CONSULTATION,
    urgencyLevel: 2,
    clinicianAssessor: 'Dr. Sarah Vance, MD',
    arrivalTimestamp: Date.now() - 75 * 60 * 1000,
    consultationStartTimestamp: Date.now() - 40 * 60 * 1000,
    completionTimestamp: null,
    vitals: {
      bloodPressureSystolic: 112,
      bloodPressureDiastolic: 70,
      heartRate: 134,
      respiratoryRate: 20,
      spO2: 96,
      temperatureC: 36.5,
      painScore: 3,
    },
    preliminaryWarningFlags: [
      'Rapid Arrhythmia (HR > 130 bpm)',
      'Geriatric Fall / Syncope Risk',
    ],
    clinicianNotes: 'Atrial fibrillation with rapid ventricular response confirmed. Rate control medication initiated.',
    roomOrBed: 'Cardiac Monitor Bay 2',
  },
  {
    id: 'pt-011',
    mrn: 'SC-2026-9910',
    fullName: 'Maria Santos',
    age: 51,
    gender: 'Female',
    phone: '+1 (555) 654-3210',
    department: 'General Medicine',
    chiefComplaint: 'Post-op dressing check and prescription refill for antibiotics',
    status: PATIENT_STATUS.WAITING,
    urgencyLevel: 5,
    clinicianAssessor: 'Triage Nurse K. Adams, RN',
    arrivalTimestamp: Date.now() - 18 * 60 * 1000,
    consultationStartTimestamp: null,
    completionTimestamp: null,
    vitals: {
      bloodPressureSystolic: 120,
      bloodPressureDiastolic: 80,
      heartRate: 70,
      respiratoryRate: 14,
      spO2: 99,
      temperatureC: 36.6,
      painScore: 1,
    },
    preliminaryWarningFlags: [],
    clinicianNotes: 'Clean healing surgical incision. Awaiting physician script sign-off.',
    roomOrBed: 'Triage Waiting Area',
  },
  {
    id: 'pt-012',
    mrn: 'SC-2026-1049',
    fullName: 'Liam Hemsworth-Smith',
    age: 41,
    gender: 'Male',
    phone: '+1 (555) 987-6543',
    department: 'Cardiology',
    chiefComplaint: 'Discharged following negative stress test and resolved atypical chest pain',
    status: PATIENT_STATUS.COMPLETED,
    urgencyLevel: 3,
    clinicianAssessor: 'Dr. Michael Chen, MD',
    arrivalTimestamp: Date.now() - 180 * 60 * 1000,
    consultationStartTimestamp: Date.now() - 120 * 60 * 1000,
    completionTimestamp: Date.now() - 45 * 60 * 1000,
    vitals: {
      bloodPressureSystolic: 126,
      bloodPressureDiastolic: 82,
      heartRate: 78,
      respiratoryRate: 16,
      spO2: 98,
      temperatureC: 36.9,
      painScore: 0,
    },
    preliminaryWarningFlags: [],
    clinicianNotes: 'Serial troponins negative. Outpatient follow-up booked with primary care.',
    roomOrBed: 'Discharged Home',
  },
];
